export const Database = [
  {
    jugadores: [
      {
        id: 1,
        nombre: "Roberto Milan",
      },
      {
        id: 2,
        nombre: "Jose Icarte",
      },
      {
        id: 3,
        nombre: "Jorge Marambio",
      },
      {
        id: 4,
        nombre: "Marcos Salazar",
      },
      {
        id: 5,
        nombre: "Alvaro Gonzalez",
      },
      {
        id: 6,
        nombre: "Nabor Riquelme",
      },
      {
        id: 7,
        nombre: "Vikingo",
      },
      {
        id: 8,
        nombre: "Jona",
      },
      {
        id: 9,
        nombre: "Serghio Torreblanca",
      },
      {
        id: 10,
        nombre: "Claudio Acuna",
      },
      {
        id: 11,
        nombre: "Carlos del Pino",
      },
      {
        id: 12,
        nombre: "Fernando",
      },
      {
        id: 13,
        nombre: "Pablo Rodriguez",
      },
      {
        id: 14,
        nombre: "Sebastian",
      },
      {
        id: 15,
        nombre: "Jose Luis Santander",
      },
      {
        id: 16,
        nombre: "Nelson Loyola",
      },
      {
        id: 17,
        nombre: "Jose Galaz",
      },
      {
        id: 18,
        nombre: "Matias Perez",
      },
      {
        id: 19,
        nombre: "Matias Pizarro",
      },
      {
        id: 20,
        nombre: "Cesar Godoy",
      },
      {
        id: 21,
        nombre: "Sebastian Sepulveda",
      },
      {
        id: 22,
        nombre: "Reinaldo Riffo",
      },
      {
        id: 23,
        nombre: "Christian Vidal",
      },
    ],

    partidos: [
      {
        id: 1,
        jugador1_id: 7,
        jugador2_id: 14,
        resultado: "6-0,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "1",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 7,
      },
      {
        id: 2,
        jugador1_id: 13,
        jugador2_id: 14,
        resultado: "6-2,6-3",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "5",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 13,
      },
      {
        id: 3,
        jugador1_id: 9,
        jugador2_id: 14,
        resultado: "6-2,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "2",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 9,
      },
      {
        id: 4,
        jugador1_id: 11,
        jugador2_id: 14,
        resultado: "6-2,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 11,
      },
      {
        id: 5,
        jugador1_id: 4,
        jugador2_id: 22,
        resultado: "6-3,7-5",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "8",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 4,
      },
      {
        id: 6,
        jugador1_id: 4,
        jugador2_id: 3,
        resultado: "6-3,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 4,
      },
      {
        id: 7,
        jugador1_id: 4,
        jugador2_id: 1,
        resultado: "6-3,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "5",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 3,
        id_jugador_ganador: 4,
      },
      {
        id: 8,
        jugador1_id: 4,
        jugador2_id: 19,
        resultado: "6-4,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "5",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 5,
        id_jugador_ganador: 4,
      },
      {
        id: 9,
        jugador1_id: 17,
        jugador2_id: 21,
        resultado: "6-4,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 17,
      },
      {
        id: 10,
        jugador1_id: 17,
        jugador2_id: 18,
        resultado: "6-1,6-3",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 17,
      },
      {
        id: 11,
        jugador1_id: 17,
        jugador2_id: 20,
        resultado: "6-2,6-4",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 3,
        id_jugador_ganador: 17,
      },
      {
        id: 12,
        jugador1_id: 23,
        jugador2_id: 17,
        resultado: "7-6,6-4",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "10",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 23,
      },
      {
        id: 13,
        jugador1_id: 10,
        jugador2_id: 3,
        resultado: "6-2,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 10,
      },
      {
        id: 14,
        jugador1_id: 9,
        jugador2_id: 10,
        resultado: "7-5,1-6,10-7",
        juegosGanadosJugador1: "18",
        juegosGanadosJugador2: "18",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 2,
        id_jugador_ganador: 9,
      },
      {
        id: 15,
        jugador1_id: 10,
        jugador2_id: 7,
        resultado: "6-3,6-3",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 3,
        id_jugador_ganador: 10,
      },
      {
        id: 16,
        jugador1_id: 10,
        jugador2_id: 5,
        resultado: "6-1,7-5",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 10,
      },
      {
        id: 17,
        jugador1_id: 12,
        jugador2_id: 5,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 12,
      },
      {
        id: 18,
        jugador1_id: 5,
        jugador2_id: 6,
        resultado: "7-5,6-4",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "9",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 5,
      },
      {
        id: 19,
        jugador1_id: 8,
        jugador2_id: 5,
        resultado: "5-7,6-2,6-4",
        juegosGanadosJugador1: "17",
        juegosGanadosJugador2: "13",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 3,
        id_jugador_ganador: 8,
      },
      {
        id: 20,
        jugador1_id: 21,
        jugador2_id: 22,
        resultado: "6-3,4-6,10-8",
        juegosGanadosJugador1: "20",
        juegosGanadosJugador2: "17",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 3,
        id_jugador_ganador: 21,
      },
      {
        id: 21,
        jugador1_id: 19,
        jugador2_id: 21,
        resultado: "6-2,7-6",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "8",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 19,
      },
      {
        id: 22,
        jugador1_id: 1,
        jugador2_id: 6,
        resultado: "6-1,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "2",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 1,
      },
      {
        id: 23,
        jugador1_id: 6,
        jugador2_id: 3,
        resultado: "2-6,6-0,6-4",
        juegosGanadosJugador1: "14",
        juegosGanadosJugador2: "10",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 4,
        id_jugador_ganador: 6,
      },
      {
        id: 24,
        jugador1_id: 16,
        jugador2_id: 9,
        resultado: "6-1,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "1",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 16,
      },
      {
        id: 25,
        jugador1_id: 12,
        jugador2_id: 9,
        resultado: "6-0,6-4",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 3,
        id_jugador_ganador: 12,
      },
      {
        id: 26,
        jugador1_id: 19,
        jugador2_id: 2,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 19,
      },
      {
        id: 27,
        jugador1_id: 19,
        jugador2_id: 20,
        resultado: "6-4,4-6,6-3",
        juegosGanadosJugador1: "18",
        juegosGanadosJugador2: "13",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 2,
        id_jugador_ganador: 19,
      },
      {
        id: 28,
        jugador1_id: 23,
        jugador2_id: 19,
        resultado: "6-0,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "1",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 3,
        id_jugador_ganador: 23,
      },
      {
        id: 29,
        jugador1_id: 7,
        jugador2_id: 8,
        resultado: "2-6,6-4,6-4",
        juegosGanadosJugador1: "14",
        juegosGanadosJugador2: "14",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 1,
        id_jugador_ganador: 7,
      },
      {
        id: 30,
        jugador1_id: 1,
        jugador2_id: 8,
        resultado: "5-7,7-6,10-8",
        juegosGanadosJugador1: "22",
        juegosGanadosJugador2: "21",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 2,
        id_jugador_ganador: 1,
      },
      {
        id: 31,
        jugador1_id: 16,
        jugador2_id: 11,
        resultado: "6-3,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 3,
        id_jugador_ganador: 16,
      },
      {
        id: 32,
        jugador1_id: 23,
        jugador2_id: 15,
        resultado: "6-3,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 23,
      },
      {
        id: 33,
        jugador1_id: 16,
        jugador2_id: 15,
        resultado: "6-0,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "1",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 16,
      },
      {
        id: 34,
        jugador1_id: 15,
        jugador2_id: 18,
        resultado: "4-6,7-6,10-6",
        juegosGanadosJugador1: "21",
        juegosGanadosJugador2: "18",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 3,
        id_jugador_ganador: 15,
      },
      {
        id: 35,
        jugador1_id: 20,
        jugador2_id: 15,
        resultado: "6-4,3-6,11-9",
        juegosGanadosJugador1: "20",
        juegosGanadosJugador2: "18",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 4,
        id_jugador_ganador: 20,
      },
      {
        id: 36,
        jugador1_id: 16,
        jugador2_id: 13,
        resultado: "6-4,7-5",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "9",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 16,
      },
      {
        id: 37,
        jugador1_id: 23,
        jugador2_id: 22,
        resultado: "6-0,6-4",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 23,
      },
    ],
  },
];
