export const Database = [
  {
    jugadores: [
      {
        id: 1,
        nombre: "Roberto Milan",
        isActivo: true,
      },
      {
        id: 2,
        nombre: "Jose Icarte",
        isActivo: false,
      },
      {
        id: 3,
        nombre: "Jorge Marambio",
        isActivo: true,
      },
      {
        id: 4,
        nombre: "Marcos Salazar",
        isActivo: true,
      },
      {
        id: 5,
        nombre: "Alvaro Gonzalez",
        isActivo: true,
      },
      {
        id: 6,
        nombre: "Nabor Riquelme",
        isActivo: true,
      },
      {
        id: 7,
        nombre: "Vikingo",
        isActivo: true,
      },
      {
        id: 8,
        nombre: "Jona",
        isActivo: true,
      },
      {
        id: 9,
        nombre: "Serghio Torreblanca",
        isActivo: true,
      },
      {
        id: 10,
        nombre: "Claudio Acuna",
        isActivo: true,
      },
      {
        id: 11,
        nombre: "Carlos del Pino",
        isActivo: true,
      },
      {
        id: 12,
        nombre: "Fernando",
        isActivo: false,
      },
      {
        id: 13,
        nombre: "Pablo Rodriguez",
        isActivo: true,
      },
      {
        id: 14,
        nombre: "Sebastian",
        isActivo: false,
      },
      {
        id: 15,
        nombre: "Jose Luis Santander",
        isActivo: true,
      },
      {
        id: 16,
        nombre: "Nelson Loyola",
        isActivo: true,
      },
      {
        id: 17,
        nombre: "Jose Galaz",
        isActivo: true,
      },
      {
        id: 18,
        nombre: "Matias Perez",
        isActivo: true,
      },
      {
        id: 19,
        nombre: "Matias Pizarro",
        isActivo: true,
      },
      {
        id: 20,
        nombre: "Cesar Godoy",
        isActivo: true,
      },
      {
        id: 21,
        nombre: "Sebastian Sepulveda",
        isActivo: true,
      },
      {
        id: 22,
        nombre: "Reinaldo Riffo",
        isActivo: true,
      },
      {
        id: 23,
        nombre: "Christian Vidal",
        isActivo: false,
      },
      {
        id: 24,
        nombre: "Ninguno",
        isActivo: false,
      },
    ],

    partidos: [
      {
        id: 1,
        jugador1_id: 7,
        jugador2_id: 14,
        resultado: "6-0,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "1",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 7,
      },
      {
        id: 2,
        jugador1_id: 13,
        jugador2_id: 14,
        resultado: "6-2,6-3",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "5",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 13,
      },
      {
        id: 3,
        jugador1_id: 9,
        jugador2_id: 14,
        resultado: "6-2,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "2",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 9,
      },
      {
        id: 4,
        jugador1_id: 11,
        jugador2_id: 14,
        resultado: "6-2,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 3,
        id_jugador_ganador: 11,
      },
      {
        id: 5,
        jugador1_id: 4,
        jugador2_id: 22,
        resultado: "6-3,7-5",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "8",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 4,
      },
      {
        id: 6,
        jugador1_id: 4,
        jugador2_id: 3,
        resultado: "6-3,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 4,
      },
      {
        id: 7,
        jugador1_id: 4,
        jugador2_id: 1,
        resultado: "6-3,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "5",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 3,
        id_jugador_ganador: 4,
      },
      {
        id: 8,
        jugador1_id: 4,
        jugador2_id: 19,
        resultado: "6-4,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "5",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 5,
        id_jugador_ganador: 4,
      },
      {
        id: 9,
        jugador1_id: 17,
        jugador2_id: 21,
        resultado: "6-4,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 17,
      },
      {
        id: 10,
        jugador1_id: 17,
        jugador2_id: 18,
        resultado: "6-1,6-3",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 17,
      },
      {
        id: 11,
        jugador1_id: 17,
        jugador2_id: 20,
        resultado: "6-2,6-4",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 3,
        id_jugador_ganador: 17,
      },
      {
        id: 12,
        jugador1_id: 23,
        jugador2_id: 17,
        resultado: "7-6,6-4",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "10",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 23,
      },
      {
        id: 13,
        jugador1_id: 10,
        jugador2_id: 3,
        resultado: "6-2,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 10,
      },
      {
        id: 14,
        jugador1_id: 9,
        jugador2_id: 10,
        resultado: "7-5,1-6,10-7",
        juegosGanadosJugador1: "18",
        juegosGanadosJugador2: "18",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 2,
        id_jugador_ganador: 9,
      },
      {
        id: 15,
        jugador1_id: 10,
        jugador2_id: 7,
        resultado: "6-3,6-3",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 3,
        id_jugador_ganador: 10,
      },
      {
        id: 16,
        jugador1_id: 10,
        jugador2_id: 5,
        resultado: "6-1,7-5",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 10,
      },
      {
        id: 17,
        jugador1_id: 12,
        jugador2_id: 5,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 12,
      },
      {
        id: 18,
        jugador1_id: 5,
        jugador2_id: 6,
        resultado: "7-5,6-4",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "9",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 5,
      },
      {
        id: 19,
        jugador1_id: 8,
        jugador2_id: 5,
        resultado: "5-7,6-2,6-4",
        juegosGanadosJugador1: "17",
        juegosGanadosJugador2: "13",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 3,
        id_jugador_ganador: 8,
      },
      {
        id: 20,
        jugador1_id: 21,
        jugador2_id: 22,
        resultado: "6-3,4-6,10-8",
        juegosGanadosJugador1: "20",
        juegosGanadosJugador2: "17",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 3,
        id_jugador_ganador: 21,
      },
      {
        id: 21,
        jugador1_id: 19,
        jugador2_id: 21,
        resultado: "6-2,7-6",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "8",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 19,
      },
      {
        id: 22,
        jugador1_id: 1,
        jugador2_id: 6,
        resultado: "6-1,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "2",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 1,
      },
      {
        id: 23,
        jugador1_id: 6,
        jugador2_id: 3,
        resultado: "2-6,6-0,6-4",
        juegosGanadosJugador1: "14",
        juegosGanadosJugador2: "10",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 3,
        id_jugador_ganador: 6,
      },
      {
        id: 24,
        jugador1_id: 16,
        jugador2_id: 9,
        resultado: "6-1,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "1",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 16,
      },
      {
        id: 25,
        jugador1_id: 12,
        jugador2_id: 9,
        resultado: "6-0,6-4",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 3,
        id_jugador_ganador: 12,
      },
      {
        id: 26,
        jugador1_id: 19,
        jugador2_id: 2,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 19,
      },
      {
        id: 27,
        jugador1_id: 19,
        jugador2_id: 20,
        resultado: "6-4,4-6,6-3",
        juegosGanadosJugador1: "18",
        juegosGanadosJugador2: "13",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 2,
        id_jugador_ganador: 19,
      },
      {
        id: 28,
        jugador1_id: 23,
        jugador2_id: 19,
        resultado: "6-0,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "1",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 3,
        id_jugador_ganador: 23,
      },
      {
        id: 29,
        jugador1_id: 7,
        jugador2_id: 8,
        resultado: "2-6,6-4,6-4",
        juegosGanadosJugador1: "14",
        juegosGanadosJugador2: "14",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 2,
        id_jugador_ganador: 7,
      },
      {
        id: 30,
        jugador1_id: 1,
        jugador2_id: 8,
        resultado: "5-7,7-6,10-8",
        juegosGanadosJugador1: "22",
        juegosGanadosJugador2: "21",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 1,
        id_jugador_ganador: 1,
      },
      {
        id: 31,
        jugador1_id: 16,
        jugador2_id: 11,
        resultado: "6-3,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 16,
      },
      {
        id: 32,
        jugador1_id: 23,
        jugador2_id: 15,
        resultado: "6-3,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 23,
      },
      {
        id: 33,
        jugador1_id: 16,
        jugador2_id: 15,
        resultado: "6-0,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "1",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 16,
      },
      {
        id: 34,
        jugador1_id: 15,
        jugador2_id: 18,
        resultado: "4-6,7-6,10-6",
        juegosGanadosJugador1: "21",
        juegosGanadosJugador2: "18",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 3,
        id_jugador_ganador: 15,
      },
      {
        id: 35,
        jugador1_id: 20,
        jugador2_id: 15,
        resultado: "6-4,3-6,11-9",
        juegosGanadosJugador1: "20",
        juegosGanadosJugador2: "18",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 4,
        id_jugador_ganador: 20,
      },
      {
        id: 36,
        jugador1_id: 16,
        jugador2_id: 13,
        resultado: "6-4,7-5",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "9",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 3,
        id_jugador_ganador: 16,
      },
      {
        id: 37,
        jugador1_id: 23,
        jugador2_id: 22,
        resultado: "6-0,6-4",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 23,
      },
      {
        id: 38,
        jugador1_id: 1,
        jugador2_id: 2,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 1,
      },
      {
        id: 39,
        jugador1_id: 18,
        jugador2_id: 11,
        resultado: "6-2,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "3",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 1,
        id_jugador_ganador: 18,
      },
      {
        id: 40,
        jugador1_id: 12,
        jugador2_id: 11,
        resultado: "6-0,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "1",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 2,
        id_jugador_ganador: 12,
      },
      {
        id: 41,
        jugador1_id: 21,
        jugador2_id: 15,
        resultado: "6-3,1-6,6-2",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "11",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 5,
        id_jugador_ganador: 21,
      },
      {
        id: 42,
        jugador1_id: 16,
        jugador2_id: 7,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 5,
        id_jugador_ganador: 16,
      },
      {
        id: 43,
        jugador1_id: 12,
        jugador2_id: 7,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 12,
      },
      {
        id: 44,
        jugador1_id: 20,
        jugador2_id: 13,
        resultado: "5-7,7-5,7-5",
        juegosGanadosJugador1: "19",
        juegosGanadosJugador2: "17",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 1,
        id_jugador_ganador: 20,
      },
      {
        id: 45,
        jugador1_id: 18,
        jugador2_id: 13,
        resultado: "6-2,7-6",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "8",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 18,
      },
      {
        id: 46,
        jugador1_id: 23,
        jugador2_id: 13,
        resultado: "6-2,6-4",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 5,
        id_jugador_ganador: 23,
      },
      {
        id: 47,
        jugador1_id: 8,
        jugador2_id: 9,
        resultado: "6-1,6-3",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 5,
        id_jugador_ganador: 8,
      },
      {
        id: 48,
        jugador1_id: 1,
        jugador2_id: 10,
        resultado: "6-3,6-4",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "7",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 5,
        id_jugador_ganador: 1,
      },
      {
        id: 49,
        jugador1_id: 22,
        jugador2_id: 6,
        resultado: "6-4,6-4",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "8",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 5,
        id_jugador_ganador: 22,
      },
      {
        id: 50,
        jugador1_id: 8,
        jugador2_id: 3,
        resultado: "6-3,2-6,6-3",
        juegosGanadosJugador1: "14",
        juegosGanadosJugador2: "12",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 4,
        id_jugador_ganador: 8,
      },
      {
        id: 51,
        jugador1_id: 5,
        jugador2_id: 14,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 5,
        id_jugador_ganador: 5,
      },
      {
        id: 52,
        jugador1_id: 20,
        jugador2_id: 11,
        resultado: "6-1,7-5",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 5,
        id_jugador_ganador: 20,
      },
      {
        id: 53,
        jugador1_id: 18,
        jugador2_id: 7,
        resultado: "7-5,2-6,10-5",
        juegosGanadosJugador1: "19",
        juegosGanadosJugador2: "16",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 6,
        id_jugador_ganador: 18,
      },
      {
        id: 54,
        jugador1_id: 13,
        jugador2_id: 21,
        resultado: "6-4,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 6,
        id_jugador_ganador: 13,
      },
      {
        id: 55,
        jugador1_id: 12,
        jugador2_id: 1,
        resultado: "4-6,6-4,10-8",
        juegosGanadosJugador1: "20",
        juegosGanadosJugador2: "18",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 6,
        id_jugador_ganador: 12,
      },
      {
        id: 56,
        jugador1_id: 20,
        jugador2_id: 9,
        resultado: "6-0,3-6,11-9",
        juegosGanadosJugador1: "20",
        juegosGanadosJugador2: "15",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 6,
        id_jugador_ganador: 20,
      },
      {
        id: 57,
        jugador1_id: 19,
        jugador2_id: 6,
        resultado: "6-0,6-3",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "3",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 6,
        id_jugador_ganador: 19,
      },
      {
        id: 58,
        jugador1_id: 8,
        jugador2_id: 22,
        resultado: "7-5,5-7,10-6",
        juegosGanadosJugador1: "22",
        juegosGanadosJugador2: "18",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 6,
        id_jugador_ganador: 8,
      },
      {
        id: 59,
        jugador1_id: 12,
        jugador2_id: 3,
        resultado: "6-0,6-3",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "3",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 5,
        id_jugador_ganador: 12,
      },
      {
        id: 60,
        jugador1_id: 17,
        jugador2_id: 4,
        resultado: "6-4,2-6,6-1",
        juegosGanadosJugador1: "14",
        juegosGanadosJugador2: "11",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 6,
        id_jugador_ganador: 17,
      },
      {
        id: 61,
        jugador1_id: 21,
        jugador2_id: 11,
        resultado: "7-5,6-2",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "7",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 7,
        id_jugador_ganador: 21,
      },
      {
        id: 62,
        jugador1_id: 5,
        jugador2_id: 18,
        resultado: "7-5,1-6,14-12",
        juegosGanadosJugador1: "22",
        juegosGanadosJugador2: "23",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 7,
        id_jugador_ganador: 5,
      },
      {
        id: 63,
        jugador1_id: 4,
        jugador2_id: 15,
        resultado: "7-5,6-1",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 7,
        id_jugador_ganador: 4,
      },
      {
        id: 64,
        jugador1_id: 9,
        jugador2_id: 23,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 7,
        id_jugador_ganador: 9,
      },
      {
        id: 65,
        jugador1_id: 17,
        jugador2_id: 2,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 5,
        id_jugador_ganador: 17,
      },
      {
        id: 66,
        jugador1_id: 5,
        jugador2_id: 16,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 6,
        id_jugador_ganador: 5,
      },
      {
        id: 67,
        jugador1_id: 22,
        jugador2_id: 2,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 4,
        id_jugador_ganador: 22,
      },
      {
        id: 68,
        jugador1_id: 10,
        jugador2_id: 22,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 7,
        id_jugador_ganador: 10,
      },
      {
        id: 69,
        jugador1_id: 15,
        jugador2_id: 2,
        resultado: "6-0,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "1",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 6,
        id_jugador_ganador: 15,
      },
      {
        id: 70,
        jugador1_id: 3,
        jugador2_id: 14,
        resultado: "6-1,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "1",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 6,
        id_jugador_ganador: 3,
      },
      {
        id: 71,
        jugador1_id: 13,
        jugador2_id: 2,
        resultado: "6-0,5-0",
        juegosGanadosJugador1: "11",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 7,
        id_jugador_ganador: 13,
      },
      {
        id: 72,
        jugador1_id: 19,
        jugador2_id: 8,
        resultado: "6-7,6-1,7-6",
        juegosGanadosJugador1: "19",
        juegosGanadosJugador2: "14",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 7,
        id_jugador_ganador: 19,
      },
      {
        id: 73,
        jugador1_id: 17,
        jugador2_id: 6,
        resultado: "6-1,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "2",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 7,
        id_jugador_ganador: 17,
      },
      {
        id: 74,
        jugador1_id: 20,
        jugador2_id: 7,
        resultado: "6-3,6-3",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 7,
        id_jugador_ganador: 20,
      },
      {
        id: 75,
        jugador1_id: 1,
        jugador2_id: 14,
        resultado: "7-5,6-0",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "5",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 7,
        id_jugador_ganador: 1,
      },
      {
        id: 76,
        jugador1_id: 18,
        jugador2_id: 3,
        resultado: "6-1,5-7,6-3",
        juegosGanadosJugador1: "17",
        juegosGanadosJugador2: "11",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 8,
        id_jugador_ganador: 18,
      },
      {
        id: 77,
        jugador1_id: 11,
        jugador2_id: 2,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 8,
        id_jugador_ganador: 11,
      },
      {
        id: 78,
        jugador1_id: 4,
        jugador2_id: 13,
        resultado: "6-1,4-6,10-3",
        juegosGanadosJugador1: "20",
        juegosGanadosJugador2: "10",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 8,
        id_jugador_ganador: 4,
      },
      {
        id: 79,
        jugador1_id: 17,
        jugador2_id: 8,
        resultado: "6-0,4-6,10-7",
        juegosGanadosJugador1: "20",
        juegosGanadosJugador2: "13",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 8,
        id_jugador_ganador: 17,
      },
      {
        id: 80,
        jugador1_id: 16,
        jugador2_id: 1,
        resultado: "6-1,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "3",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 8,
        id_jugador_ganador: 16,
      },
      {
        id: 81,
        jugador1_id: 19,
        jugador2_id: 10,
        resultado: "6-3,6-7,10-8",
        juegosGanadosJugador1: "19",
        juegosGanadosJugador2: "18",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 8,
        id_jugador_ganador: 19,
      },
      {
        id: 82,
        jugador1_id: 21,
        jugador2_id: 9,
        resultado: "6-3,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "3",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 8,
        id_jugador_ganador: 21,
      },
      {
        id: 83,
        jugador1_id: 9,
        jugador2_id: 2,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 9,
        id_jugador_ganador: 9,
      },
      {
        id: 84,
        jugador1_id: 16,
        jugador2_id: 3,
        resultado: "6-1,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "2",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 7,
        id_jugador_ganador: 16,
      },
      {
        id: 85,
        jugador1_id: 20,
        jugador2_id: 5,
        resultado: "7-6,6-4",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "10",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 8,
        id_jugador_ganador: 20,
      },
      {
        id: 86,
        jugador1_id: 21,
        jugador2_id: 7,
        resultado: "6-1,7-6",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "7",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 9,
        id_jugador_ganador: 21,
      },
      {
        id: 87,
        jugador1_id: 8,
        jugador2_id: 15,
        resultado: "7-5,6-4",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "9",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 9,
        id_jugador_ganador: 8,
      },
      {
        id: 88,
        jugador1_id: 17,
        jugador2_id: 10,
        resultado: "6-3,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "5",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 9,
        id_jugador_ganador: 17,
      },
      {
        id: 89,
        jugador1_id: 20,
        jugador2_id: 3,
        resultado: "5-7,6-1,10-6",
        juegosGanadosJugador1: "22",
        juegosGanadosJugador2: "14",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 9,
        id_jugador_ganador: 20,
      },
      {
        id: 90,
        jugador1_id: 22,
        jugador2_id: 12,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 8,
        id_jugador_ganador: 22,
      },
      {
        id: 91,
        jugador1_id: 13,
        jugador2_id: 6,
        resultado: "6-1,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "2",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 9,
        id_jugador_ganador: 13,
      },
      {
        id: 92,
        jugador1_id: 12,
        jugador2_id: 19,
        resultado: "6-3,6-4",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "7",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 9,
        id_jugador_ganador: 12,
      },
      {
        id: 93,
        jugador1_id: 12,
        jugador2_id: 17,
        resultado: "6-4,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "5",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 10,
        id_jugador_ganador: 12,
      },
      {
        id: 94,
        jugador1_id: 20,
        jugador2_id: 1,
        resultado: "6-2,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 10,
        id_jugador_ganador: 20,
      },
      {
        id: 95,
        jugador1_id: 22,
        jugador2_id: 14,
        resultado: "6-1,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "2",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 9,
        id_jugador_ganador: 22,
      },
      {
        id: 96,
        jugador1_id: 15,
        jugador2_id: 10,
        resultado: "7-6,4-1",
        juegosGanadosJugador1: "11",
        juegosGanadosJugador2: "7",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 10,
        id_jugador_ganador: 15,
      },
      {
        id: 97,
        jugador1_id: 21,
        jugador2_id: 5,
        resultado: "7-5,7-5",
        juegosGanadosJugador1: "14",
        juegosGanadosJugador2: "10",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 10,
        id_jugador_ganador: 21,
      },
      {
        id: 98,
        jugador1_id: 10,
        jugador2_id: 11,
        resultado: "6-2,6-4",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "6",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 11,
        id_jugador_ganador: 10,
      },
      {
        id: 99,
        jugador1_id: 4,
        jugador2_id: 11,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 9,
        id_jugador_ganador: 4,
      },
      {
        id: 100,
        jugador1_id: 4,
        jugador2_id: 9,
        resultado: "6-2,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 10,
        id_jugador_ganador: 4,
      },
      {
        id: 101,
        jugador1_id: 1,
        jugador2_id: 18,
        resultado: "5-7,6-3,10-3",
        juegosGanadosJugador1: "21",
        juegosGanadosJugador2: "13",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 9,
        id_jugador_ganador: 1,
      },
      {
        id: 102,
        jugador1_id: 4,
        jugador2_id: 5,
        resultado: "6-3,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "3",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 11,
        id_jugador_ganador: 4,
      },
      {
        id: 103,
        jugador1_id: 15,
        jugador2_id: 14,
        resultado: "6-0,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "1",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 11,
        id_jugador_ganador: 15,
      },
      {
        id: 104,
        jugador1_id: 16,
        jugador2_id: 20,
        resultado: "6-1,6-3",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "4",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 12,
        id_jugador_ganador: 16,
      },
      {
        id: 105,
        jugador1_id: 19,
        jugador2_id: 14,
        resultado: "6-3,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "3",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 10,
        id_jugador_ganador: 19,
      },
      {
        id: 106,
        jugador1_id: 21,
        jugador2_id: 1,
        resultado: "7-6,6-4",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "10",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 11,
        id_jugador_ganador: 21,
      },
      {
        id: 107,
        jugador1_id: 10,
        jugador2_id: 2,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 12,
        id_jugador_ganador: 10,
      },
      {
        id: 108,
        jugador1_id: 6,
        jugador2_id: 7,
        resultado: "6-4,6-4",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "8",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 11,
        id_jugador_ganador: 6,
      },
      {
        id: 109,
        jugador1_id: 16,
        jugador2_id: 17,
        resultado: "6-2,7-6",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "8",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 11,
        id_jugador_ganador: 16,
      },
      {
        id: 110,
        jugador1_id: 13,
        jugador2_id: 9,
        resultado: "6-1,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "2",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 12,
        id_jugador_ganador: 13,
      },
      {
        id: 111,
        jugador1_id: 17,
        jugador2_id: 5,
        resultado: "6-1,6-2",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "3",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 12,
        id_jugador_ganador: 17,
      },
      {
        id: 112,
        jugador1_id: 21,
        jugador2_id: 12,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 12,
        id_jugador_ganador: 21,
      },
      {
        id: 113,
        jugador1_id: 13,
        jugador2_id: 12,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 11,
        id_jugador_ganador: 13,
      },
      {
        id: 114,
        jugador1_id: 10,
        jugador2_id: 18,
        resultado: "6-2,6-3",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "5",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 13,
        id_jugador_ganador: 10,
      },
      {
        id: 115,
        jugador1_id: 19,
        jugador2_id: 3,
        resultado: "2-6,6-3,7-5",
        juegosGanadosJugador1: "15",
        juegosGanadosJugador2: "14",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 12,
        id_jugador_ganador: 19,
      },
      {
        id: 116,
        jugador1_id: 19,
        jugador2_id: 18,
        resultado: "6-4,5-7,6-3",
        juegosGanadosJugador1: "17",
        juegosGanadosJugador2: "14",
        setGanadosJugador1: "2",
        setGanadosJugador2: "1",
        fecha: 11,
        id_jugador_ganador: 19,
      },
      {
        id: 117,
        jugador1_id: 23,
        jugador2_id: 3,
        resultado: "6-1,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "2",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 10,
        id_jugador_ganador: 23,
      },
      {
        id: 118,
        jugador1_id: 3,
        jugador2_id: 2,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 11,
        id_jugador_ganador: 3,
      },
      {
        id: 119,
        jugador1_id: 21,
        jugador2_id: 14,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 13,
        id_jugador_ganador: 21,
      },
      {
        id: 120,
        jugador1_id: 19,
        jugador2_id: 1,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 13,
        id_jugador_ganador: 19,
      },
      {
        id: 121,
        jugador1_id: 4,
        jugador2_id: 8,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 12,
        id_jugador_ganador: 4,
      },
      {
        id: 122,
        jugador1_id: 5,
        jugador2_id: 15,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 13,
        id_jugador_ganador: 5,
      },
      {
        id: 123,
        jugador1_id: 8,
        jugador2_id: 11,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 13,
        id_jugador_ganador: 8,
      },
      {
        id: 124,
        jugador1_id: 13,
        jugador2_id: 7,
        resultado: "6-0,6-1",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "1",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 13,
        id_jugador_ganador: 13,
      },
      {
        id: 125,
        jugador1_id: 1,
        jugador2_id: 22,
        resultado: "7-6,6-4",
        juegosGanadosJugador1: "13",
        juegosGanadosJugador2: "10",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 12,
        id_jugador_ganador: 1,
      },
      {
        id: 126,
        jugador1_id: 22,
        jugador2_id: 20,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 11,
        id_jugador_ganador: 22,
      },
      {
        id: 127,
        jugador1_id: 15,
        jugador2_id: 6,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 8,
        id_jugador_ganador: 15,
      },
      {
        id: 127,
        jugador1_id: 6,
        jugador2_id: 11,
        resultado: "6-0,6-0",
        juegosGanadosJugador1: "12",
        juegosGanadosJugador2: "0",
        setGanadosJugador1: "2",
        setGanadosJugador2: "0",
        fecha: 10,
        id_jugador_ganador: 6,
      },
    ],
    fechasLibres: [
      {
        idJugador: 6,
        fecha: 1,
      },
      {
        idJugador: 21,
        fecha: 2,
      },
      {
        idJugador: 2,
        fecha: 3,
      },
      {
        idJugador: 4,
        fecha: 4,
      },
      {
        idJugador: 18,
        fecha: 5,
      },
      {
        idJugador: 10,
        fecha: 6,
      },
      {
        idJugador: 12,
        fecha: 7,
      },
      {
        idJugador: 14,
        fecha: 8,
      },
      {
        idJugador: 16,
        fecha: 9,
      },
      {
        idJugador: 8,
        fecha: 10,
      },
      {
        idJugador: 23,
        fecha: 11,
      },
      {
        idJugador: 11,
        fecha: 12,
      },
      {
        idJugador: 24,
        fecha: 13,
      },
      {
        idJugador: 11,
        fecha: 14,
      },
      {
        idJugador: 20,
        fecha: 15,
      },
    ],
    calendario: [
      {
        idFecha: 1,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 8,
          },
          {
            jugador1_id: 3,
            jugador2_id: 10,
          },
          {
            jugador1_id: 5,
            jugador2_id: 12,
          },
          {
            jugador1_id: 7,
            jugador2_id: 14,
          },
          {
            jugador1_id: 9,
            jugador2_id: 16,
          },
          {
            jugador1_id: 11,
            jugador2_id: 18,
          },
          {
            jugador1_id: 13,
            jugador2_id: 20,
          },
          {
            jugador1_id: 15,
            jugador2_id: 23,
          },
          {
            jugador1_id: 17,
            jugador2_id: 21,
          },
          {
            jugador1_id: 19,
            jugador2_id: 2,
          },
          {
            jugador1_id: 22,
            jugador2_id: 4,
          },
        ],
      },
      {
        idFecha: 2,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 2,
          },
          {
            jugador1_id: 3,
            jugador2_id: 4,
          },
          {
            jugador1_id: 5,
            jugador2_id: 6,
          },
          {
            jugador1_id: 7,
            jugador2_id: 8,
          },
          {
            jugador1_id: 9,
            jugador2_id: 10,
          },
          {
            jugador1_id: 11,
            jugador2_id: 12,
          },
          {
            jugador1_id: 13,
            jugador2_id: 14,
          },
          {
            jugador1_id: 15,
            jugador2_id: 16,
          },
          {
            jugador1_id: 17,
            jugador2_id: 18,
          },
          {
            jugador1_id: 19,
            jugador2_id: 20,
          },
          {
            jugador1_id: 22,
            jugador2_id: 23,
          },
        ],
      },
      {
        idFecha: 3,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 4,
          },
          {
            jugador1_id: 3,
            jugador2_id: 6,
          },
          {
            jugador1_id: 5,
            jugador2_id: 8,
          },
          {
            jugador1_id: 7,
            jugador2_id: 10,
          },
          {
            jugador1_id: 9,
            jugador2_id: 12,
          },
          {
            jugador1_id: 11,
            jugador2_id: 14,
          },
          {
            jugador1_id: 13,
            jugador2_id: 16,
          },
          {
            jugador1_id: 15,
            jugador2_id: 18,
          },
          {
            jugador1_id: 17,
            jugador2_id: 20,
          },
          {
            jugador1_id: 19,
            jugador2_id: 23,
          },
          {
            jugador1_id: 21,
            jugador2_id: 22,
          },
        ],
      },
      {
        idFecha: 4,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 6,
          },
          {
            jugador1_id: 3,
            jugador2_id: 8,
          },
          {
            jugador1_id: 5,
            jugador2_id: 10,
          },
          {
            jugador1_id: 7,
            jugador2_id: 12,
          },
          {
            jugador1_id: 9,
            jugador2_id: 14,
          },
          {
            jugador1_id: 11,
            jugador2_id: 16,
          },
          {
            jugador1_id: 13,
            jugador2_id: 18,
          },
          {
            jugador1_id: 15,
            jugador2_id: 20,
          },
          {
            jugador1_id: 17,
            jugador2_id: 23,
          },
          {
            jugador1_id: 19,
            jugador2_id: 21,
          },
          {
            jugador1_id: 22,
            jugador2_id: 2,
          },
        ],
      },
      {
        idFecha: 5,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 10,
          },
          {
            jugador1_id: 3,
            jugador2_id: 12,
          },
          {
            jugador1_id: 5,
            jugador2_id: 14,
          },
          {
            jugador1_id: 7,
            jugador2_id: 16,
          },
          {
            jugador1_id: 9,
            jugador2_id: 8,
          },
          {
            jugador1_id: 11,
            jugador2_id: 20,
          },
          {
            jugador1_id: 13,
            jugador2_id: 23,
          },
          {
            jugador1_id: 15,
            jugador2_id: 21,
          },
          {
            jugador1_id: 17,
            jugador2_id: 2,
          },
          {
            jugador1_id: 19,
            jugador2_id: 4,
          },
          {
            jugador1_id: 22,
            jugador2_id: 6,
          },
        ],
      },
      {
        idFecha: 6,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 12,
          },
          {
            jugador1_id: 3,
            jugador2_id: 14,
          },
          {
            jugador1_id: 5,
            jugador2_id: 16,
          },
          {
            jugador1_id: 7,
            jugador2_id: 18,
          },
          {
            jugador1_id: 9,
            jugador2_id: 20,
          },
          {
            jugador1_id: 11,
            jugador2_id: 23,
          },
          {
            jugador1_id: 13,
            jugador2_id: 21,
          },
          {
            jugador1_id: 15,
            jugador2_id: 2,
          },
          {
            jugador1_id: 17,
            jugador2_id: 4,
          },
          {
            jugador1_id: 19,
            jugador2_id: 6,
          },
          {
            jugador1_id: 22,
            jugador2_id: 8,
          },
        ],
      },
      {
        idFecha: 7,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 14,
          },
          {
            jugador1_id: 3,
            jugador2_id: 16,
          },
          {
            jugador1_id: 5,
            jugador2_id: 18,
          },
          {
            jugador1_id: 7,
            jugador2_id: 20,
          },
          {
            jugador1_id: 9,
            jugador2_id: 23,
          },
          {
            jugador1_id: 11,
            jugador2_id: 21,
          },
          {
            jugador1_id: 13,
            jugador2_id: 2,
          },
          {
            jugador1_id: 15,
            jugador2_id: 4,
          },
          {
            jugador1_id: 17,
            jugador2_id: 6,
          },
          {
            jugador1_id: 19,
            jugador2_id: 8,
          },
          {
            jugador1_id: 22,
            jugador2_id: 10,
          },
        ],
      },
      {
        idFecha: 8,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 16,
          },
          {
            jugador1_id: 3,
            jugador2_id: 18,
          },
          {
            jugador1_id: 5,
            jugador2_id: 20,
          },
          {
            jugador1_id: 7,
            jugador2_id: 23,
          },
          {
            jugador1_id: 9,
            jugador2_id: 21,
          },
          {
            jugador1_id: 11,
            jugador2_id: 2,
          },
          {
            jugador1_id: 13,
            jugador2_id: 4,
          },
          {
            jugador1_id: 15,
            jugador2_id: 6,
          },
          {
            jugador1_id: 17,
            jugador2_id: 8,
          },
          {
            jugador1_id: 19,
            jugador2_id: 10,
          },
          {
            jugador1_id: 22,
            jugador2_id: 12,
          },
        ],
      },
      {
        idFecha: 9,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 18,
          },
          {
            jugador1_id: 3,
            jugador2_id: 20,
          },
          {
            jugador1_id: 5,
            jugador2_id: 23,
          },
          {
            jugador1_id: 7,
            jugador2_id: 21,
          },
          {
            jugador1_id: 9,
            jugador2_id: 2,
          },
          {
            jugador1_id: 11,
            jugador2_id: 4,
          },
          {
            jugador1_id: 13,
            jugador2_id: 6,
          },
          {
            jugador1_id: 15,
            jugador2_id: 8,
          },
          {
            jugador1_id: 17,
            jugador2_id: 10,
          },
          {
            jugador1_id: 19,
            jugador2_id: 12,
          },
          {
            jugador1_id: 22,
            jugador2_id: 14,
          },
        ],
      },
      {
        idFecha: 10,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 20,
          },
          {
            jugador1_id: 3,
            jugador2_id: 23,
          },
          {
            jugador1_id: 5,
            jugador2_id: 21,
          },
          {
            jugador1_id: 7,
            jugador2_id: 2,
          },
          {
            jugador1_id: 9,
            jugador2_id: 4,
          },
          {
            jugador1_id: 11,
            jugador2_id: 6,
          },
          {
            jugador1_id: 13,
            jugador2_id: 18,
          },
          {
            jugador1_id: 15,
            jugador2_id: 10,
          },
          {
            jugador1_id: 17,
            jugador2_id: 12,
          },
          {
            jugador1_id: 19,
            jugador2_id: 14,
          },
          {
            jugador1_id: 22,
            jugador2_id: 16,
          },
        ],
      },
      {
        idFecha: 11,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 21,
          },
          {
            jugador1_id: 3,
            jugador2_id: 2,
          },
          {
            jugador1_id: 5,
            jugador2_id: 4,
          },
          {
            jugador1_id: 7,
            jugador2_id: 6,
          },
          {
            jugador1_id: 9,
            jugador2_id: 8,
          },
          {
            jugador1_id: 11,
            jugador2_id: 10,
          },
          {
            jugador1_id: 13,
            jugador2_id: 12,
          },
          {
            jugador1_id: 15,
            jugador2_id: 14,
          },
          {
            jugador1_id: 17,
            jugador2_id: 16,
          },
          {
            jugador1_id: 19,
            jugador2_id: 18,
          },
          {
            jugador1_id: 22,
            jugador2_id: 20,
          },
        ],
      },
      {
        idFecha: 12,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 22,
          },
          {
            jugador1_id: 3,
            jugador2_id: 19,
          },
          {
            jugador1_id: 5,
            jugador2_id: 17,
          },
          {
            jugador1_id: 7,
            jugador2_id: 15,
          },
          {
            jugador1_id: 9,
            jugador2_id: 13,
          },
          {
            jugador1_id: 8,
            jugador2_id: 4,
          },
          {
            jugador1_id: 10,
            jugador2_id: 2,
          },
          {
            jugador1_id: 12,
            jugador2_id: 21,
          },
          {
            jugador1_id: 14,
            jugador2_id: 23,
          },
          {
            jugador1_id: 16,
            jugador2_id: 20,
          },
          {
            jugador1_id: 6,
            jugador2_id: 18,
          },
        ],
      },
      {
        idFecha: 13,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 19,
          },
          {
            jugador1_id: 3,
            jugador2_id: 17,
          },
          {
            jugador1_id: 5,
            jugador2_id: 15,
          },
          {
            jugador1_id: 7,
            jugador2_id: 13,
          },
          {
            jugador1_id: 10,
            jugador2_id: 18,
          },
          {
            jugador1_id: 8,
            jugador2_id: 11,
          },
          {
            jugador1_id: 16,
            jugador2_id: 23,
          },
          {
            jugador1_id: 14,
            jugador2_id: 21,
          },
          {
            jugador1_id: 20,
            jugador2_id: 6,
          },
          {
            jugador1_id: 12,
            jugador2_id: 4,
          },
          {
            jugador1_id: 22,
            jugador2_id: 9,
          },
        ],
      },
      {
        idFecha: 14,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 17,
          },
          {
            jugador1_id: 3,
            jugador2_id: 9,
          },
          {
            jugador1_id: 5,
            jugador2_id: 13,
          },
          {
            jugador1_id: 7,
            jugador2_id: 19,
          },
          {
            jugador1_id: 16,
            jugador2_id: 21,
          },
          {
            jugador1_id: 20,
            jugador2_id: 4,
          },
          {
            jugador1_id: 22,
            jugador2_id: 15,
          },
          {
            jugador1_id: 10,
            jugador2_id: 8,
          },
          {
            jugador1_id: 6,
            jugador2_id: 18,
          },
        ],
      },
      {
        idFecha: 15,
        partidos: [
          {
            jugador1_id: 1,
            jugador2_id: 3,
          },
          {
            jugador1_id: 4,
            jugador2_id: 6,
          },
          {
            jugador1_id: 5,
            jugador2_id: 7,
          },
          {
            jugador1_id: 8,
            jugador2_id: 16,
          },
          {
            jugador1_id: 9,
            jugador2_id: 11,
          },
          {
            jugador1_id: 10,
            jugador2_id: 13,
          },
          {
            jugador1_id: 15,
            jugador2_id: 19,
          },
          {
            jugador1_id: 17,
            jugador2_id: 22,
          },
          {
            jugador1_id: 18,
            jugador2_id: 21,
          },
        ],
      },
    ],
  },
];
